name: Build and Test
on:
  push:
    paths-ignore:
      - '.github/workflows/make-release.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'
      - '.circleci/**'
      - 'LICENSE'
      - 'CNAME'
      - 'README.md'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set environments
        run: |
          {
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
          } >> $GITHUB_ENV

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repo }}@${{ env.commit }}
          path: target/JMusicBot-Snapshot-All.jar
          if-no-files-found: error
