name: Make Release
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'     
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: false
        type: string

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Set Version
        run: sed -e 's/Snapshot/${{ github.event.inputs.version_number }}/' -i pom.xml

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set environments
        run: echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})" >> $GITHUB_ENV

      - name: Rename JAR
        run: mv target/JMusicBot-${{ github.event.inputs.version_number }}-All.jar JMusicBot-${{ github.event.inputs.version_number }}.jar

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version_number }}
          name: Version ${{ github.event.inputs.version_number }}
          draft: true
          prerelease: false
          files: JMusicBot-${{ github.event.inputs.version_number }}.jar
          body: |
            ${{ github.event.inputs.info }}
            
            ---
            ### Setup
            https://jmusicbot.com/setup  
            https://jmusicbot.com/config  
            # Download: [JMusicBot-${{ github.event.inputs.version_number }}.jar](https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.version_number }}/JMusicBot-${{ github.event.inputs.version_number }}.jar)
